### ISSUE TITLE
Support additional constructor arguments in app.register

### ISSUE THREAD

**Issue by taion** [martyjs/marty-lib#10]
`Application#register` gives a natural hook to pass in extra arguments to constructors for various classes. Does it make sense to add this feature?

**Comment by ntkoso** [comment]
Yes, i think it is a good idea.

``` javascript
new Application(outsideInitialState);

class Application extends Marty.Application {
  constructor(outsideInitialState) {
    super();
    this.register('someStore', SomeStore, outsideInitialState.someStore);
  }
}

class SomeStore extends Marty.Store {
  constructor(initialState) {
    super();
    this.state = initialState || {};
  }
}
```

Usecase when you need to inject some data before `Application#renderToString` on server side.

**Comment by taion** [comment]
No longer relevant.

**Comment by brandondoran** [comment]
@taion Is this no longer relevant because there's a different/better way to accomplish? I'm basically wanting to initialize a store with state before server side renderToString.  I'm not seeing any clear way to do this.  Am I missing something? I realize this is not being actively maintained anymore. Thank you.

**Comment by taion** [comment]
It's not relevant because this project is dead.
