### ISSUE TITLE
Builds failing in IE <= 10

### ISSUE THREAD

**Issue by jhollingworth** [martyjs/marty-lib#4]
https://travis-ci.org/martyjs/marty-lib/builds/62897390

@taion any thoughts?

**Comment by taion** [comment]
Ah, I see that IE <= 10 doesn't have `.__proto__`. One sec - might not have time to fix this until later tonight.

**Comment by taion** [comment]
Okay, turns out static inheritance just doesn't work as implemented on Babel with IE <= 10, without enabling an extra optional transform: https://babeljs.io/docs/usage/caveats/#classes-10-and-below-

I think this is a cool enough feature to be worth having, but I'm not happy with an approach that would require everyone to use a specific optional extra Babel transform. One other option might be to have some separate method (maybe `Marty.registerStatic` or something) instead of making it a static method on the class itself.

**Comment by jhollingworth** [comment]
I'm not a massive fan of the name `registerStatic` but I agree having a static on `Marty` is likely the best solution. I'm becoming quite a fan of decorators so I'm wondering if a more declarative name would make sense?

e.g.

``` js
let { dependency } = require('marty');

@dependency('userStore')
class UserStore extends Marty.Store {

}

module.exports = UserStore;
```

**Comment by taion** [comment]
I'm fine with whatever name. I was planning on using currying, so that

``` js
dependency(Application, 'userStore', UserStore);
dependency(Application, 'userStore')(UserStore);
dependency(Application)('userStore')(UserStore);
```

all do exactly the same thing, and the latter two could be used as decorators on `UserStore` (as could just `dependency(Application)` on its own, if you don't need the custom name).

Thing is, while this makes registrations fairly nice and pretty close to what's in v0.9.x, even with injection from containers, it's still a bit more verbose to access Stores and ActionCreators from components, so this doesn't fully accomplish what I'm looking for.

**Comment by jhollingworth** [comment]
out of interest, how do you plan on requiring in all the dependencies? Will you require in the dependency into each component but not use it?

``` js
require('../stores/userStore');

class User extends React.Component {
}
```

or do a mass require before application start?

``` js
require('./stores/fooStore');
require('./actions/fooActions');
...
```

**Comment by taion** [comment]
Shoot, I hadn't thought through that part. There'd be no point to it being anything other than (1), but that's really finicky and doesn't quite work, and (2) is no better than just putting all the registrations in the constructor.

The only way to make (1) work would be to pass in the class itself to something like `app.get(...)`, to avoid having unused imports/variables, but that doesn't work if you name these dependencies.

Maybe we're better off backing this out for now. I'm going to prototype something with continuation locals that might give me the best of both worlds and see how that turns out.

**Comment by jhollingworth** [comment]
OK cool, removed for now :smile:
